[project]
build_dir = "build"

[[fpga]]
name = "main"
fpga_part = "xc7a35tcpg236-1"

[[ip]]
name = "axi_pulse_cntrl"
sources = [
	"./srcs/rtl/if_axi_lite.sv",
	"./srcs/rtl/axi_pulse_cntrl.sv"
]

[[wrapper]]
ip = "axi_pulse_cntrl"
sources = [
	"./srcs/rtl/if_axi_lite.sv",
	"./srcs/rtl/axi_pulse_cntrl.sv"
]

[[bd]]
name = "bd_mblaze_system"

[[synth]]
bd           = "bd_mblaze_system"
constraints  = ["./constraints/system.xdc"]
run_synth    = true
run_opt      = true
run_place    = true
run_phys_opt = true
run_route    = true
synth_incremental = true
impl_incremental = true
route_report_timing_summary = true
synth_report_utilization    = true
route_report_drc            = true

[[platform]]
name = "mb_platform"
bd   = "bd_mblaze_system"
cpu  = "microblaze_0"
os   = "standalone"

[[app]]
name     = "firmware"
platform = "mb_platform"
template = "empty_application"
sources  = ["./srcs/sw/main.c"]



[[simulation]]
name      = "tb_axi_pulse_cntrl"
top       = "tb_axi_pulse_cntrl"
backend   = "xsim"
timescale = "1ns/1ps"
sources   = [
	"./srcs/rtl/if_axi_lite.sv",
	"./srcs/rtl/axi_pulse_cntrl.sv",
	"./srcs/sim/tb_axi_pulse_cntrl.sv"
]
